mon_ds:
    resource: "@MonDsBundle/Resources/config/routing.yml"
    prefix:   /monds

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /fob

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
